### ISSUE TITLE
Bump deps to deal with ghc 8.6? 

### ISSUE THREAD

**Issue by gbaz** [diagrams/diagrams-graphviz#9]
https://matrix.hackage.haskell.org/#/package/diagrams-graphviz

**Comment by georgefst** [comment]
Came here to ask this as well (indeed 8.8 is now out too...). Seems to work on 8.6 after bumping bounds on a few dependencies, but I haven't tested extensively.

**Comment by byorgey** [comment]
Thanks, apologies for the radio silence on my end.  I'm currently working through a big backlog of upper bounds bumps etc., hopefully within the next few days everything in the diagrams ecosystem should be updated for GHC 8.8.
